dist: jammy
sudo: false
addons:
  ssh_known_hosts: nick.bewegung.jetzt
script:
- echo "kewl"

before_deploy:
- openssl aes-256-cbc -K $encrypted_697b8c654e27_key -iv $encrypted_697b8c654e27_iv -in .ci/id.key.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@nick.bewegung.jetzt:/var/dib/portal/build
  on:
    branch: master
    condition: '"$TRAVIS_PULL_REQUEST" = "false"'
